version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my-network
    volumes:
      - ./backend:/backend

  # 頼むから.env使ってくれ...
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # ホットリロードを行う設定
    depends_on:
      - backend
    networks:
      - my-network
    volumes:
      - ./frontend:/frontend

volumes:
  db-data:

networks:
  my-network: